### ISSUE TITLE
Basic CLI functionality

### ISSUE THREAD

**Issue by mattykay** [mattykay/pybix#2]
## Request
Some basic CLI functionality should be included to accept either arguments as input or config file.

E.g. `python -m pybix host.get` should return all hosts.
or `python -c config.json` to get all CPI graphs for server 1 as per below config.json;
```json
{
    "graphimage": [
        {
            "type": "graphname",
            "name": "CPU",
            "hosts": ["server1"]
        }
    ]
}
```

## TODO

- [x] Allow spaces in input string (e.g. `item_names="agent availability")
- [ ] Consider --individual flag to interpret inputs to create multiple graphs not one consolidated/meaningless graph
- [ ] Ensure list/dictionary conversion occurring as expected

**Comment by mattykay** [comment]
Woops.. appears various CLI inputs aren't supported or function as intended;

1. key="value with spaces" isn't supported and should be
```
$ pybix graphimage.item_names item_names=availability host_names="[cme-aumhd-zab01,cme-aumhd-zab02]"
2019-08-20 14:20:39,353:__main__:ERROR:Unable to interpret arguments, should be like: key1=value1 or key2="{value2:[subvalue1, subvalue2]}" or key3="{value3:subvalue3}"
```

2. graph.item_X methods consolidate to one ad-hoc graph, will need to think how to handle, perhaps 1 item per 1 host. (e.g. below consolidated 4 items per 2 hosts into one unreadable graph)
```
$ pybix graphimage.item_names item_names=availability host_names="[cme-aumhd-zab01,cme-aumhd-zab02]"
```

3. Neither output argument or filter below is returned as expected. Appears filter value not passed correctly (but `{'filter':'name=Unix/NEC'}` NOT `{'filter':{'name':['Unix/NEC']}` )
```
#  Invalid for both filter/output
$ pybix hostgroup.get filter="name=Unix/NEC" output=name

# However output when below works
$ pybix hostgroup.get filter="name=Unix/NEC" output=[name]
```

Good reminder to add more unit testing :)
